CREATE TABLE IF NOT EXISTS weather_data (
    clouds_percentage INT,
    co_ords_lat FLOAT,
    co_ords_lon FLOAT,
    dt TIMESTAMP,
    feels_like FLOAT,
    humidity INT,
    pressure INT,
    temp FLOAT,
    temp_max FLOAT,
    temp_min FLOAT,
    city VARCHAR(255),
    country VARCHAR(255),
    sunrise TIMESTAMP,
    sunset TIMESTAMP,
    timezone TIMESTAMP,
    weather_description VARCHAR(255),
    weather_main VARCHAR(255),
    wind_deg INT,
    wind_speed FLOAT
);